# Generated by Django 5.2.5 on 2025-10-13 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_student_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValorantApplicationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='Enable or disable Valorant applications')),
            ],
        ),
        migrations.CreateModel(
            name='ValorantApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_ign', models.CharField(help_text='Discord IGN (e.g., username#1234)', max_length=100)),
                ('riot_ign', models.CharField(help_text='Riot IGN (e.g., username#NA1)', max_length=100)),
                ('contact_number', models.CharField(help_text='Contact number for the team captain', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='valorant_application', to='registration.student')),
            ],
        ),
    ]
