# Generated by Django 5.2.5 on 2025-10-13 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_valorantapplicationsettings_valorantapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValorantTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_ign', models.CharField(help_text='Discord IGN (e.g., username#1234)', max_length=100)),
                ('riot_ign', models.CharField(help_text='Riot IGN (e.g., username#NA1)', max_length=100)),
                ('contact_number', models.CharField(help_text='Contact number for the team member', max_length=20)),
                ('team_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='valorant_info', to='registration.teammember')),
            ],
        ),
    ]
