# Generated by Django 5.2.5 on 2025-11-15 14:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_valorantteammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bundle_type', models.CharField(choices=[('JUNIOR', 'Titanium Junior Innovators Pack (Grade 3-6)'), ('SENIOR', 'Titanium Senior Visionaries Pack (Grade 7-12)')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('badge_color', models.CharField(default='blue', help_text="Tailwind color class (e.g., 'blue', 'purple', 'green')", max_length=50)),
                ('icon', models.CharField(default='fa-star', help_text="FontAwesome icon class (e.g., 'fa-star', 'fa-rocket')", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_grade', models.ForeignKey(help_text='Maximum grade for this bundle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bundles_max', to='registration.grade')),
                ('min_grade', models.ForeignKey(help_text='Minimum grade for this bundle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bundles_min', to='registration.grade')),
            ],
            options={
                'verbose_name': 'Discount Bundle',
                'verbose_name_plural': 'Discount Bundles',
                'ordering': ['display_order', 'bundle_type'],
            },
        ),
        migrations.CreateModel(
            name='BundleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('event_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_inclusions', to='registration.eventoption')),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_events', to='registration.discountbundle')),
            ],
            options={
                'verbose_name': 'Bundle Event',
                'verbose_name_plural': 'Bundle Events',
                'ordering': ['display_order'],
                'unique_together': {('bundle', 'event_option')},
            },
        ),
        migrations.AddField(
            model_name='student',
            name='selected_bundle',
            field=models.ForeignKey(blank=True, help_text='Discount bundle selected by student (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='registration.discountbundle'),
        ),
        migrations.DeleteModel(
            name='ValorantApplication',
        ),
    ]
